Repository Mocamp-Official/Mocamp-FrontEnd, pull requests merged in 2025-07, with the labels that each got.

#38 ✨ feat : 웹 캠 프리뷰 & 방 생성 페이지 연결 & 기타 로직 추가
  package-lock.json
  package.json
  public/svgs/VoiceIcon.svg
  public/svgs/webcamcamera.svg
  src/apis/room.ts
  src/apis/signal.ts
  src/components/create-room/CreateRoom.tsx
  src/components/create/CreateRoom.tsx
  src/components/create/ImageUploadBox.tsx
  src/components/create/LabeledBox.tsx
  src/components/create/NumberInput.tsx
  src/components/create/ToggleMicButton.tsx
  src/components/onBoarding/SlideCard1.tsx
  src/components/onBoarding/SlideCard2.tsx
  src/components/onBoarding/SlideCard3.tsx
  src/components/webcamPreview/Buttons.tsx
  src/components/webcamPreview/Cam.tsx
  src/components/webcamPreview/RoomInfo.tsx
  src/components/webcamPreview/WebCamMedia.tsx
  src/components/webcamPreview/WebCamPreview.tsx
  src/hooks/useMediaDevices.ts
  src/hooks/useWebRTC.ts
  src/pages/preview/[id].tsx
  src/stores/rtcstore.ts
  src/types/preview.ts
  src/types/rtc.ts
  src/utils/decode.ts
Labels: feature UI

#49 ✨ feat: 메인 작업 공간 방 관련 웹소켓 연결 로직 추가 및 UI 추가 (미완료)
  package-lock.json
  package.json
  src/apis/room.ts
  src/components/Header/CreateJoinHeader.tsx
  src/components/WebCam/WebCam.tsx
  src/components/WebCam/modal/DelegationModal.tsx
  src/components/WebCam/modal/NotDelegationModal.tsx
  src/components/todo/TodoSection.tsx
  src/components/webcamPreview/Cam.tsx
  src/hooks/useGroupCall.ts
  src/hooks/useWebRTC.ts
  src/libs/groupcallsignal.ts
  src/pages/room/[id].tsx
  src/stores/rtcstore.ts
  src/types/room.ts
  tsconfig.json
Labels: feature UI, feature logic

#50 ✨ feat: 마이홈 UI & 세부 기능 추가
  next.config.ts
  public/svgs/mocamp_gray_icon.svg
  src/apis/myhome.ts
  src/components/Header/CreateJoinHeader.tsx
  src/components/myhome/MocampUsageTrend.tsx
  src/components/myhome/ParticipantedMocamp.tsx
  src/components/myhome/SideBar.tsx
  src/components/myhome/Total.tsx
  src/components/myhome/content/GoalDetailItem.tsx
  src/components/myhome/content/GoalDetailList.tsx
  src/components/myhome/content/GoalGraph.tsx
  src/components/myhome/content/GoalList.tsx
  src/components/myhome/content/ParticipantedMocampItem.tsx
  src/components/myhome/content/ParticipantedMocampModal.tsx
  src/components/myhome/content/ParticipatedCard.tsx
  src/components/myhome/content/TimeGraph.tsx
  src/constants/routes.ts
  src/hooks/useMocampTimer.ts
  src/pages/api/auth/.gitkeep
  src/pages/myhome.tsx
  src/stores/myhome-store.ts
  src/styles/globals.css
  src/types/myhome.ts
  src/utils/timeUtils.ts
Labels: feature UI, feature logic, update

#55 💄 Design: 컬러 수정 및 오류 수정
  package.json
  public/svgs/UnlockIcon.svg
  public/svgs/defaultProfile.svg
  src/apis/room.ts
  src/components/common/modal/CommonModal.tsx
  src/components/create-room/CreateRoom.tsx
  src/components/create-room/ImageUploadBox.tsx
  src/components/create/CreateRoom.tsx
  src/components/create/ImageUploadBox.tsx
  src/components/create/LabeledBox.tsx
  src/components/create/NumberInput.tsx
  src/components/create/ToggleMicButton.tsx
  src/components/todo/modal/GoalModalWrapper.tsx
  src/components/todo/progress/MoreMenu.tsx
  src/hooks/useGroupCall.ts
Labels: feature UI, update

#58 ✨ feat: 프리뷰 최종 완성
  src/components/create-room/CreateRoom.tsx
  src/components/webcamPreview/Cam.tsx
  src/components/webcamPreview/RoomInfo.tsx
  src/components/webcamPreview/WebCamPreview.tsx
  src/hooks/useGroupCall.ts
  src/hooks/useRoomForm.ts
  src/pages/create.tsx
  src/pages/preview/[id].tsx
  src/pages/room/[id].tsx
  src/stores/create.ts
  src/stores/roomForm-store.ts
  src/types/preview.ts
  src/types/room.ts
Labels: feature UI, feature logic, update

#59 🎨 Design: 로그인 페이지 반응형 적용
  src/components/auth/GoogleLoginButton.tsx
  src/components/auth/KakaoLoginButton.tsx
  src/components/auth/NaverLoginButton.tsx
  src/pages/login.tsx
Labels: feature UI, update

#61 ✨ Feat: 모바일 감지 라이브러리 설치 및 모바일일 경우 보이는 UI 구현
  package-lock.json
  package.json
  src/components/layout/ResponsiveLayout.tsx
  src/pages/_app.tsx
Labels: feature UI, feature logic

#66 🐛 Fix: 웹소켓 연결 로직 수정
  package-lock.json
  package.json
  src/components/Header/WorkSpaceHeader.tsx
  src/components/Sidebar/RoomEndNotice.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/todo/TodoCard.tsx
  src/components/todo/TodoSection.tsx
  src/components/todo/modal/GoalModalWrapper.tsx
  src/components/todo/progress/ProgressCard.tsx
  src/components/webcamPreview/RoomInfo.tsx
  src/hooks/room/useRoomContext.ts
  src/hooks/room/useRoomPublisher.ts
  src/hooks/room/useRoomSync.ts
  src/pages/room/[id].tsx
  src/stores/todo-store.ts
Labels: bug, feature logic

#67 Design: 헤더 스타일 수정
  src/components/Header/OnboardingHeader.tsx
Labels: update

#72 ✨ feat: 튜토리얼 UI 추가
  next.config.ts
  public/svgs/goal_gauge.svg
  src/components/WebCam/tutorial/Tutorial.tsx
  src/components/WebCam/tutorial/Tutorial1.tsx
  src/components/WebCam/tutorial/Tutorial2.tsx
  src/components/WebCam/tutorial/Tutorial3.tsx
  src/components/WebCam/tutorial/TutorialBackground.tsx
  src/components/myhome/SideBar.tsx
  src/components/myhome/Total.tsx
  src/components/myhome/content/ProfileModal.tsx
  src/pages/room/[id].tsx
  src/stores/myhome-store.ts
  src/stores/tutorial-store.ts
Labels: feature UI, refactoring
