Repository Mocamp-Official/Mocamp-FrontEnd, pull requests merged in 2025-05, with the labels that each got.

#7 ✨ feat: 로그인 페이지 UI 구현
  next.config.ts
  package-lock.json
  package.json
  public/svgs/MocampIcon.svg
  src/components/auth/GoogleLoginButton.tsx
  src/components/auth/KakaoLoginButton.tsx
  src/components/auth/NaverLoginButton.tsx
  src/pages/api/auth/.gitkeep
  src/pages/login.tsx
  tsconfig.json
Labels: feature UI

#20 🔧 Chore: PR 템플릿 수정
  .github/pull_request_template.md
Labels: update

#8 ✨ feat: 투두리스트 UI 구현
  src/components/todo/TodoCard.tsx
  src/components/todo/TodoContainer.tsx
  src/components/todo/TodoNoContent.tsx
  src/components/todo/TodoSecretContent.tsx
  src/components/todo/progress/ProgressBadge.tsx
  src/components/todo/progress/ProgressBar.tsx
  src/components/todo/progress/ProgressCard.tsx
  src/components/todo/progress/ProgressText.tsx
  src/pages/main.tsx
  src/styles/globals.css
Labels: feature UI

#26 ✨ feat: 로그인 API 연결 및 최근 로그인 기능 구현
  .prettierrc
  next.config.ts
  src/apis/auth.ts
  src/apis/axios.ts
  src/components/auth/GoogleLoginButton.tsx
  src/components/auth/KakaoLoginButton.tsx
  src/components/auth/NaverLoginButton.tsx
  src/components/auth/OAtuhCallback.tsx
  src/components/auth/SocialLogin.tsx
  src/pages/login.tsx
  src/pages/myhome.tsx
  src/stores/auth-store.ts
  src/stores/authStore.ts
  src/types/auth.ts
  src/utils/token.ts
Labels: feature UI, feature logic

#25 ✨ feat: 사이드바 UI 구현
  package-lock.json
  package.json
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarExitButton.tsx
  src/components/Sidebar/SidebarParticipants.tsx
  src/components/Sidebar/SidebarTimer.tsx
  src/components/Sidebar/modal/SidebarExitModal.tsx
  src/hooks/useMocampTimer.ts
  src/hooks/useParticipants.ts
  src/pages/main.tsx
  src/utils/timeUtils.ts
Labels: feature UI

#27 ✨ feat: 메인 작업 공간 모달 UI 구현
  package-lock.json
  package.json
  public/svgs/CloseButton.svg
  public/svgs/PencilIcon.svg
  public/svgs/TodoMoreIcon.svg
  public/svgs/UnsecretIcon.svg
  src/components/common/modal/CommonModal.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/todo/TodoCard.tsx
  src/components/todo/TodoContainer.tsx
  src/components/todo/TodoEmptyContent.tsx
  src/components/todo/TodoNoContent.tsx
  src/components/todo/TodoSecretContent.tsx
  src/components/todo/TodoSection.tsx
  src/components/todo/modal/GoalModalContent.tsx
  src/components/todo/modal/GoalModalWrapper.tsx
  src/components/todo/progress/MoreMenu.tsx
  src/components/todo/progress/ProgressBadge.tsx
  src/components/todo/progress/ProgressBar.tsx
  src/components/todo/progress/ProgressCard.tsx
  src/components/todo/progress/ProgressText.tsx
  src/pages/main.tsx
  src/types/todo.ts
Labels: feature UI, feature logic
